name: Format Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  format:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run Format Check
        run: make format-check
